name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node Dependencies
        run: npm ci  # Ensures correct dependencies

      - name: Debug React Native Pods File
        run: |
          if [ ! -f "node_modules/react-native/scripts/react_native_pods.rb" ]; then
            echo "⚠️ react_native_pods.rb is missing! Reinstalling..."
            rm -rf node_modules ios/Pods
            npm ci
            cd ios && pod install --repo-update
          else
            echo "✅ react_native_pods.rb found!"
          fi

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Build and Archive iOS App
        run: |
          xcodebuild clean archive \
            -workspace ios/MyApp.xcworkspace \
            -scheme MyApp \
            -configuration Release \
            -archivePath ios/build/MyApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/MyApp.xcarchive \
            -exportPath ios/build/ \
            -exportOptionsPlist ios/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Verify IPA File
        run: |
          if [ ! -f "ios/build/MyApp.ipa" ]; then
            echo "❌ IPA file was not generated!"
            exit 1
          fi

      - name: Upload IPA to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-ipa
          path: ios/build/MyApp.ipa
          retention-days: 30
